language: c
sudo: required
notifications:
  email: false

services:
  - docker

env:
  include:
    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD bash /io/travis/build-wheels.sh
  - ls wheelhouse/
